"""add chatbot ai config

Revision ID: 511483ae6dbc
Revises: 4bedc3c71f8c
Create Date: 2026-07-18 18:52:45.834347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511483ae6dbc'
down_revision: Union[str, Sequence[str], None] = '4bedc3c71f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_ai_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OLLAMA', name='llmprovider'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('streaming', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name=op.f('fk_chatbot_ai_configs_chatbot_id_chatbots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chatbot_ai_configs')),
    sa.UniqueConstraint('chatbot_id', name=op.f('uq_chatbot_ai_configs_chatbot_id'))
    )
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_members', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_invitations_invited_by_users'), 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_invited_by_fkey'), 'invitations', 'users', ['invited_by'], ['id'])
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.alter_column('invitations', 'token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('invitations', 'invited_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('chatbot_ai_configs')
    # ### end Alembic commands ###
