"""add chatbot conversation message models

Revision ID: 73b83f906241
Revises: 511483ae6dbc
Create Date: 2026-07-19 14:43:43.260258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b83f906241'
down_revision: Union[str, Sequence[str], None] = '511483ae6dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name=op.f('fk_conversations_chatbot_id_chatbots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_conversations_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_message_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_message_role', 'messages', ['role'], unique=False)
    op.alter_column('invitations', 'invited_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invitations', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_constraint(op.f('invitations_invited_by_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invitations_invited_by_users'), 'invitations', 'users', ['invited_by'], ['id'], ondelete='CASCADE')
    op.alter_column('organization_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_members', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_invitations_invited_by_users'), 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_invited_by_fkey'), 'invitations', 'users', ['invited_by'], ['id'])
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.alter_column('invitations', 'token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('invitations', 'invited_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_message_role', table_name='messages')
    op.drop_index('ix_message_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
