"""initial schema

Revision ID: 597a3aa30a58
Revises:
Create Date: 2026-08-06 12:26:28.517118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = "597a3aa30a58"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # pgvector is required by document_chunks.embedding.
    #
    # This makes the initial migration self-contained so a fresh
    # PostgreSQL database does not require manually running:
    #
    #     CREATE EXTENSION vector;
    #
    # before running `alembic upgrade head`.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )

    op.create_index(
        op.f("ix_users_email"),
        "users",
        ["email"],
        unique=True,
    )

    op.create_index(
        op.f("ix_users_id"),
        "users",
        ["id"],
        unique=False,
    )

    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "logo",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "owner_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_organizations_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_organizations"),
        ),
    )

    op.create_index(
        op.f("ix_organizations_id"),
        "organizations",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_organizations_slug"),
        "organizations",
        ["slug"],
        unique=True,
    )

    op.create_table(
        "chatbots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "organization_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "slug",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "TRAINING",
                "READY",
                "PAUSED",
                "ARCHIVED",
                name="chatbotstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "avatar",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "welcome_message",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "placeholder_text",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "is_public",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "public_uuid",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "last_trained_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_chatbots_created_by_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_chatbots_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_chatbots"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "slug",
            name="uq_chatbot_org_slug",
        ),
        sa.UniqueConstraint(
            "public_uuid",
            name=op.f("uq_chatbots_public_uuid"),
        ),
    )

    op.create_index(
        "ix_chatbot_organization",
        "chatbots",
        ["organization_id"],
        unique=False,
    )

    op.create_index(
        "ix_chatbot_public_uuid",
        "chatbots",
        ["public_uuid"],
        unique=False,
    )

    op.create_index(
        "ix_chatbot_status",
        "chatbots",
        ["status"],
        unique=False,
    )

    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "organization_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "invited_by",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "token",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "MEMBER",
                name="organizationrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "CANCELLED",
                "EXPIRED",
                name="invitationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_invitations_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_invitations"),
        ),
    )

    op.create_index(
        op.f("ix_invitations_id"),
        "invitations",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_invitations_token"),
        "invitations",
        ["token"],
        unique=True,
    )

    op.create_table(
        "organization_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "organization_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "MEMBER",
                name="organizationrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_organization_members_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f(
                "fk_organization_members_user_id_users"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_organization_members"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            name="uq_org_user",
        ),
    )

    op.create_index(
        op.f("ix_organization_members_id"),
        "organization_members",
        ["id"],
        unique=False,
    )

    op.create_table(
        "chatbot_ai_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "chatbot_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum(
                "OPENAI",
                "ANTHROPIC",
                "GOOGLE",
                "OLLAMA",
                name="llmprovider",
            ),
            nullable=False,
        ),
        sa.Column(
            "model_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "system_prompt",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "temperature",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "max_tokens",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "streaming",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chatbot_id"],
            ["chatbots.id"],
            name=op.f(
                "fk_chatbot_ai_configs_chatbot_id_chatbots"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_chatbot_ai_configs"),
        ),
        sa.UniqueConstraint(
            "chatbot_id",
            name=op.f("uq_chatbot_ai_configs_chatbot_id"),
        ),
    )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "chatbot_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chatbot_id"],
            ["chatbots.id"],
            name=op.f(
                "fk_conversations_chatbot_id_chatbots"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f(
                "fk_conversations_created_by_users"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_conversations"),
        ),
    )

    op.create_table(
        "knowledge_bases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "chatbot_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "INDEXING",
                "READY",
                "FAILED",
                "ARCHIVED",
                name="knowledgebasestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "embedding_provider",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "embedding_model",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "chunk_size",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "chunk_overlap",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "last_indexed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chatbot_id"],
            ["chatbots.id"],
            name=op.f(
                "fk_knowledge_bases_chatbot_id_chatbots"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_knowledge_bases"),
        ),
        sa.UniqueConstraint(
            "chatbot_id",
            "name",
            name="uq_chatbot_knowledge_base_name",
        ),
    )

    op.create_index(
        "ix_kb_active",
        "knowledge_bases",
        ["is_active"],
        unique=False,
    )

    op.create_index(
        "ix_kb_chatbot",
        "knowledge_bases",
        ["chatbot_id"],
        unique=False,
    )

    op.create_index(
        "ix_kb_status",
        "knowledge_bases",
        ["status"],
        unique=False,
    )

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "knowledge_base_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "stored_filename",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "storage_path",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "content_type",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "file_size",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "PROCESSING",
                "READY",
                "FAILED",
                name="documentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f(
                "fk_documents_knowledge_base_id_knowledge_bases"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_documents"),
        ),
    )

    op.create_index(
        "ix_document_knowledge_base",
        "documents",
        ["knowledge_base_id"],
        unique=False,
    )

    op.create_index(
        "ix_document_status",
        "documents",
        ["status"],
        unique=False,
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "conversation_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM",
                "USER",
                "ASSISTANT",
                name="messagerole",
            ),
            nullable=False,
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "token_count",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f(
                "fk_messages_conversation_id_conversations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_messages"),
        ),
    )

    op.create_index(
        "ix_message_conversation",
        "messages",
        ["conversation_id"],
        unique=False,
    )

    op.create_index(
        "ix_message_role",
        "messages",
        ["role"],
        unique=False,
    )

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "document_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "chunk_index",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "token_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "embedding",
            Vector(dim=1024),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f(
                "fk_document_chunks_document_id_documents"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_document_chunks"),
        ),
        sa.UniqueConstraint(
            "document_id",
            "chunk_index",
            name="uq_document_chunk_index",
        ),
    )

    op.create_index(
        "ix_document_chunk_document",
        "document_chunks",
        ["document_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        "ix_document_chunk_document",
        table_name="document_chunks",
    )

    op.drop_table("document_chunks")

    op.drop_index(
        "ix_message_role",
        table_name="messages",
    )

    op.drop_index(
        "ix_message_conversation",
        table_name="messages",
    )

    op.drop_table("messages")

    op.drop_index(
        "ix_document_status",
        table_name="documents",
    )

    op.drop_index(
        "ix_document_knowledge_base",
        table_name="documents",
    )

    op.drop_table("documents")

    op.drop_index(
        "ix_kb_status",
        table_name="knowledge_bases",
    )

    op.drop_index(
        "ix_kb_chatbot",
        table_name="knowledge_bases",
    )

    op.drop_index(
        "ix_kb_active",
        table_name="knowledge_bases",
    )

    op.drop_table("knowledge_bases")

    op.drop_table("conversations")

    op.drop_table("chatbot_ai_configs")

    op.drop_index(
        op.f("ix_organization_members_id"),
        table_name="organization_members",
    )

    op.drop_table("organization_members")

    op.drop_index(
        op.f("ix_invitations_token"),
        table_name="invitations",
    )

    op.drop_index(
        op.f("ix_invitations_id"),
        table_name="invitations",
    )

    op.drop_table("invitations")

    op.drop_index(
        "ix_chatbot_status",
        table_name="chatbots",
    )

    op.drop_index(
        "ix_chatbot_public_uuid",
        table_name="chatbots",
    )

    op.drop_index(
        "ix_chatbot_organization",
        table_name="chatbots",
    )

    op.drop_table("chatbots")

    op.drop_index(
        op.f("ix_organizations_slug"),
        table_name="organizations",
    )

    op.drop_index(
        op.f("ix_organizations_id"),
        table_name="organizations",
    )

    op.drop_table("organizations")

    op.drop_index(
        op.f("ix_users_id"),
        table_name="users",
    )

    op.drop_index(
        op.f("ix_users_email"),
        table_name="users",
    )

    op.drop_table("users")

    # Intentionally do NOT drop the vector extension here.
    #
    # The vector extension is database-level infrastructure and may be
    # required by other applications/tables in the same PostgreSQL
    # database. Removing the schema should not remove shared infrastructure.

    # ### end Alembic commands ###