"""add knowledge sources

Revision ID: fa4c67568aa0
Revises: 60a12b34c56d
Create Date: 2026-08-15 15:23:37.177236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4c67568aa0'
down_revision: Union[str, Sequence[str], None] = '60a12b34c56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('PDF', 'DOCX', 'TXT', 'CSV', 'HTML', 'MARKDOWN', 'WEBSITE', 'NOTION', 'CONFLUENCE', 'DATABASE', 'S3', name='knowledgesourcetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='knowledgesourcestatus'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], name=op.f('fk_knowledge_sources_knowledge_base_id_knowledge_bases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources')),
    sa.UniqueConstraint('knowledge_base_id', 'name', name='uq_kb_source_name')
    )
    op.create_index('ix_knowledge_source_kb', 'knowledge_sources', ['knowledge_base_id'], unique=False)
    op.create_index('ix_knowledge_source_status', 'knowledge_sources', ['status'], unique=False)
    op.create_index('ix_knowledge_source_type', 'knowledge_sources', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_source_type', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_source_status', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_source_kb', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
